default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000

development:
  <<: *default
  username: root
  password: root
  database: sample_development

test:
  <<: *default
  username: root
  password: root
  database: sample_test

staging:
  <<: *default
  username: root
  password: root
  database: sample_staging

production:
  <<: *default
  username: root
  password: root
  database: sample_production
