---
# Set application name
#
# Default is rocker_docker
application_name: sample_app

# Set rails version
# Visit: https://hub.docker.com/_/rails/ for list of available versions
#
# Default is latest
rails_version: latest

# Set docker container's rails environment to production, staging, or development
# Make sure application is properly configured to run in 'application_env' (development)
#
# Default is development
application_env: development

# Set docker container's rails port to access from local machine
# Make sure it doesn't conflict with any of the ports active in host machine
#
# Default 5000
application_port: 5000

# Set root password for docker database container
# it doesn't make any changes in your computer's database
# It will be used only for MySQL database
#
# Default root
db_root_pass: root

# Set postgres database version if application uses postgres
# Visit: https://hub.docker.com/_/postgres/ for list of available versions
#
# Default is alpine
postgres_version: alpine

# Set mysql database version if application uses mysql
# Visit: https://hub.docker.com/_/mysql/ for list of available versions
#
# Default is latest
mysql_version: latest

# Set database properties

# Default database username for container's internal use
# It has no impact on host machine's database
# Default user
database_user_name: user

# Default database password for container's internal use
# It has no impact on host machine's database
# Default pass
database_user_pass: pass
